### ISSUE TITLE
No Edit... menu option on clean install

### ISSUE THREAD

**Issue by crankygeek** [iconmaster/menubrain#7]
I just did a clean install of 1.0.6 on MacBook Pro (16-inch, 2019) macOS 10.15.7.

Clicking on the icon in the menu bar, there's a prompt to "Click on Edit... to get started" but it's greyed out, and there's no visible Edit option.
![menubrain-first-launch](https://user-images.githubusercontent.com/1638278/117186692-f2c72c80-ad8f-11eb-8d19-347b0d49fdf3.png)

Once I saved some text to the app, Edit and Quit are available in the menu.

Possibly a separate issue: I had to copy text to MenuBrain via the Services context menu because I couldn't recall the default keyboard shortcut. Maybe that should be in the prompt text instead of "Click on Edit... to get started"? Something like "Use ⇧⌘M to add text to MenuBrain"?

**Comment by rudyrichter** [comment]
@crankygeek this is fixed in #3

**Comment by iconmaster** [comment]
@crankygeek Check [release v1.0.7](https://github.com/iconmaster/menubrain/releases/tag/v1.0.7) and see if it fixes this along with getting you custom separators.

**Comment by crankygeek** [comment]
@iconmaster LGTM
